# Generated by Django 5.2.17 on 2026-09-12 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('AGENT', 'Agent'), ('SUPERVISOR', 'Supervisor'), ('ADMINISTRATOR', 'Administrator')], default='AGENT', max_length=20),
        ),
    ]
