# Generated by Django 5.2.17 on 2026-09-11 18:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InboundMessageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('raw_headers', models.JSONField(default=dict)),
                ('match_method', models.CharField(choices=[('REPLY_TO_TOKEN', 'Reply-to token'), ('HEADERS', 'In-Reply-To / References headers'), ('SUBJECT_TOKEN', 'Subject token'), ('NONE', 'No match — new ticket created')], max_length=20)),
                ('processing_error', models.TextField(blank=True)),
                ('matched_ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inbound_logs', to='tickets.ticket')),
            ],
            options={
                'ordering': ['-received_at'],
            },
        ),
    ]
