# Generated by Django 5.2.17 on 2026-09-11 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReferenceSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefix', models.CharField(max_length=10)),
                ('year', models.PositiveIntegerField()),
                ('last_value', models.PositiveIntegerField(default=0)),
            ],
            options={
                'unique_together': {('prefix', 'year')},
            },
        ),
    ]
