# Generated by Django 5.2.17 on 2026-09-14 17:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('email_confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('language', models.CharField(choices=[('ar', 'Arabic'), ('en', 'English')], default='ar', max_length=2)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'customer account',
                'verbose_name_plural': 'customer accounts',
                'ordering': ['email'],
            },
        ),
        migrations.CreateModel(
            name='CustomerToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('purpose', models.CharField(choices=[('CONFIRMATION', 'Confirm an email address'), ('RESET', 'Reset a password')], max_length=20)),
                ('value_hash', models.CharField(db_index=True, max_length=64)),
                ('expires_at', models.DateTimeField()),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to='portal.customeraccount')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['value_hash', 'purpose'], name='portal_cust_value_h_fe0968_idx')],
            },
        ),
    ]
