# Generated by Django 5.2.17 on 2026-09-15 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeraccount',
            name='failed_sign_ins',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customeraccount',
            name='locked_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
