# Generated by Django 5.2.17 on 2026-09-12 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='channel',
            field=models.CharField(choices=[('WEB_FORM', 'Web form'), ('EMAIL', 'Email'), ('CHAT', 'Live chat')], max_length=10),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='origin_channel',
            field=models.CharField(choices=[('WEB_FORM', 'Web form'), ('EMAIL', 'Email'), ('CHAT', 'Live chat')], max_length=10),
        ),
    ]
