# Generated by Django 5.2.17 on 2026-09-15 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_alter_message_channel_alter_ticket_origin_channel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='channel',
            field=models.CharField(choices=[('WEB_FORM', 'Web form'), ('EMAIL', 'Email'), ('CHAT', 'Live chat'), ('PORTAL', 'Customer portal')], max_length=10),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='origin_channel',
            field=models.CharField(choices=[('WEB_FORM', 'Web form'), ('EMAIL', 'Email'), ('CHAT', 'Live chat'), ('PORTAL', 'Customer portal')], max_length=10),
        ),
    ]
