# Generated by Django 5.2.17 on 2026-09-13 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='end_reason',
            field=models.CharField(blank=True, choices=[('RESOLVED', 'Resolved'), ('ENDED_BY_AGENT', 'Ended by the agent'), ('ENDED_BY_VISITOR', 'Ended by the visitor'), ('VISITOR_DISCONNECTED', 'The visitor disconnected'), ('IDLE_TIMEOUT', 'Closed after inactivity'), ('DESK_CLOSED', 'The desk closed while waiting')], default='', max_length=25),
        ),
    ]
