# Generated by Django 5.2.17 on 2026-09-13 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_alter_conversation_end_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='idle_warned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
